routes/web.php
<?php


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// sitio
Route::group([
    'prefix' => '/',
    'as' => 'sitio.',
], function() {

    Route::get('', 'SitioController@inicio')->name('inicio');
    Route::get('ministerios', 'SitioController@ministerios')->name('ministerios');
    Route::get('lo_que_ensenamos', 'SitioController@loQueEnsenamos')->name('lo_que_ensenamos');
    Route::get('lideres', 'SitioController@lideres')->name('lideres');
    Route::get('testimonios', 'SitioController@testimonios')->name('testimonios');
    Route::get('contacto', 'SitioController@contacto')->name('contacto');
    Route::post('contacto', 'SitioController@mensajeContacto')->name('mensajeContacto');
    Route::post('boletin', 'SitioController@suscribirseBoletin')->name('suscribirse_boletin');
    Route::delete('boletin', 'SitioController@desuscribirseBoletin')->name('desuscribirse_boletin');

    Route::get('test', 'SitioController@test')->name('test');
});


// seccion de sermones
Route::group([
    'prefix' => 'sermones',
    'as' => 'sermones.',
], function() {

    // sermones
    Route::redirect('', config('app.url').'/sermones/sermones');
    Route::group([
        'prefix' => 'sermones',
        'as' => 'sermones.',
    ], function() {

        Route::get('', 'SermonController@index')->name('index');
        Route::get('{slug}', 'SermonController@show')->name('show');
    });

    // series
    Route::group([
        'prefix' => 'series',
        'as' => 'series.',
    ], function() {

        Route::get('', 'SerieController@index')->name('index');
        Route::get('{slug}', 'SerieController@show')->name('show');
    });

    // lideres
    Route::group([
        'prefix' => 'lideres',
        'as' => 'lideres.',
    ], function() {

        Route::get('', 'LiderController@index')->name('index');
        Route::get('{slug}', 'LiderController@show')->name('show');
    });

    // libros
    Route::group([
        'prefix' => 'libros',
        'as' => 'libros.',
    ], function() {

        Route::get('', 'LibroController@index')->name('index');
        Route::get('{libro}', 'LibroController@show')->name('show');
    });

    // medios
    Route::group([
        'prefix' => 'medios',
        'as' => 'medios.',
    ], function() {

        Route::get('{slug}', 'MedioController@show')->name('show');
    });

});


// admin
Route::group([
    'prefix' => 'admin',
    'as' => 'admin.',
    'middleware' => ['auth'],
    'namespace' => 'Admin',
], function() {

    Route::get('/', 'EscritorioController@index')->name('index');
    Route::get('/activar-transmision', 'EscritorioController@activarTransmision')->name('activar-transmision');


    // sermones
    Route::group([
        'prefix' => 'sermones',
        'as' => 'sermones.',
    ], function() {

        Route::get('', 'ASermonController@index')->name('index');
        Route::get('{slug}/edit', 'ASermonController@edit')->name('edit');
        Route::put('{slug}', 'ASermonController@update')->name('update');
        Route::get('create', 'ASermonController@create')->name('create');
        Route::post('', 'ASermonController@store')->name('store');

        // Ajax
        Route::get('todos', 'ASermonController@apiTodos')->name('apiTodos');
        Route::delete('{slug}', 'ASermonController@apiDestroy')->name('apiDestroy');
    });


    // series
    Route::group([
        'prefix' => 'series',
        'as' => 'series.',
    ], function() {

        Route::get('', 'ASerieController@index')->name('index');
        Route::get('{slug}/edit', 'ASerieController@edit')->name('edit');
        Route::put('{slug}', 'ASerieController@update')->name('update');
        Route::get('create', 'ASerieController@create')->name('create');
        Route::post('', 'ASerieController@store')->name('store');

        // Ajax
        Route::get('todos', 'ASerieController@apiTodos')->name('apiTodos');
        Route::delete('{slug}', 'ASerieController@apiDestroy')->name('apiDestroy');
    });


    // lideres
    Route::group([
        'prefix' => 'lideres',
        'as' => 'lideres.',
    ], function() {

        Route::get('', 'ALiderController@index')->name('index');
        Route::get('{slug}/edit', 'ALiderController@edit')->name('edit');
        Route::put('{slug}', 'ALiderController@update')->name('update');
        Route::get('create', 'ALiderController@create')->name('create');
        Route::post('', 'ALiderController@store')->name('store');

        // Ajax
        Route::get('todos', 'ALiderController@apiTodos')->name('apiTodos');
        Route::delete('{slug}', 'ALiderController@apiDestroy')->name('apiDestroy');
    });

    // medios
    Route::group([
        'prefix' => 'medios',
        'as' => 'medios.',
    ], function() {

        Route::get('', 'AMedioController@index')->name('index');
        Route::get('{slug}/edit', 'AMedioController@edit')->name('edit');
        Route::put('{slug}', 'AMedioController@update')->name('update');
        Route::get('create', 'AMedioController@create')->name('create');
        Route::post('', 'AMedioController@store')->name('store');

        // Ajax
        Route::get('todos', 'AMedioController@apiTodos')->name('apiTodos');
        Route::delete('{slug}', 'AMedioController@apiDestroy')->name('apiDestroy');
    });
});


Auth::routes();

resources/views/sitio/admin/lideres/create.blade.php
@extends('sitio.admin.layout.admin_master')
@section('titulo', 'Crear Líder ')
@section('admin_contenido')
  <h1>Crear Líder</h1>

  <hr>

  <form action="{{ route('admin.lideres.store') }}"
        method="POST"
        enctype="multipart/form-data">
    @csrf

    <!-- row 1 -->
    <div class="row">
      <div class="col-md-4">
        <h5>Información general</h5>
      </div>

      <div class="col-md-8">

        <div class="form-group">
          <div class="form-group">
            <label>Nombre:</label>
            <input class="form-control"
                   type="text"
                   required
                   name="nombre"
                   value="{{ old('nombre') }}">
            @if ($errors->has('nombre'))
              <div class="alert alert-danger">
                {{ $errors->first('nombre') }}
              </div>
            @endif
          </div>
        </div>

        <div class="form-group">
          <div class="form-group">
            <label>Biografía:</label>
            <textarea class="form-control"
                      name="bio"
                      rows="5"
                      value="">{{ old('bio') }}</textarea>
            @if ($errors->has('bio'))
              <div class="alert alert-danger">
                {{ $errors->first('bio') }}
              </div>
            @endif
          </div>
        </div>

        <div class="form-group">
          <label>Posición:</label>
          <select id="posicion"
                  class="selectpicker form-control"
                  title="Seleccione una opción"
                  data-live-search="true"
                  required
                  name="posicion">
            @foreach(POSICIONES as $posicion)
              <option value="{{ $posicion }}">{{ $posicion }}</option>
            @endforeach
          </select>
          @if ($errors->has('posicion'))
            <div class="alert alert-danger">
              {{ $errors->first('posicion') }}
            </div>
          @endif
        </div>

      </div>
    </div>
    <!-- fin row 1 -->

    <hr>

    <!-- row 2 -->
    <div class="row">
      <div class="col-md-4">
        <h5>Información complementaria</h5>
      </div>

      <div class="col-md-8">

        <div class="form-group">
          <label>Contacto:</label> <br>
          <small>
            <label class="text-muted">
              Ingrese una forma de contacto escribiendo el nombre de la red social,
              dos puntos (:)
              y luego el nombre de usuario. Ejemplo: <strong>instagram:luciano27</strong>.
              Ingrese varias formas de contacto separados por espacio ( ). Ejemplo:
              <strong>instagram:veritatis facebook:voluptas email:nadia81@terra.com</strong>.
            </label>
          </small>
          <input class="form-control"
                 type="text"
                 required
                 name="contacto"
                 value="{{ old('contacto') }}">
          @if ($errors->has('contacto'))
            <div class="alert alert-danger">
              {{ $errors->first('contacto') }}
            </div>
          @endif
        </div>

        <div class="form-group">
          <label>Imagen:</label>
          <div class="custom-file"
               style="display:none">
            <input id="imagen"
                   class="custom-file-input"
                   type="file"
                   name="imagen"
                   lang="es">
            <label class="custom-file-label"
                   for="imagen">Elegir imagen</label>
          </div>
          <subir-imagen>@include('parciales.cargando-img')</subir-imagen>

          @if ($errors->has('imagen'))
            <div class="alert alert-danger">
              {{ $errors->first('imagen') }}
            </div>
          @endif
        </div>

      </div>
    </div>
    <!-- fin row 2 -->

    <hr>

    <div class="d-flex justify-content-center">
      <button type="submit" class="btn btn-primary mr-2">Guardar</button>
      <a class="btn btn-secondary" href="{{ route('admin.lideres.index') }}">Cancelar</a>
    </div>

  </form>


@endsection
@push('script')
<script>
  $('#imagen').on('change',function(){
    var fileName = $(this).val().replace('C:\\fakepath\\', '');
    $(this).next('.custom-file-label').html(fileName);
  });

  // valor de dropdown posicion
  $('#posicion').val(@json(old('posicion'))
    ? @json(old('posicion'))
    : null).change();


</script>
@endpush

resources/views/sitio/admin/lideres/edit.blade.php
@extends('sitio.admin.layout.admin_master')
@section('titulo', 'Editar Líder ' . $lider->nombre)
@section('admin_contenido')
  <h1>Editar líder</h1>

  <hr>

  <form action="{{ route('admin.lideres.update', $lider->slug) }}"
        method="POST"
        enctype="multipart/form-data">
    @method('PUT')
    @csrf

    <!-- row 1 -->
    <div class="row">
      <div class="col-md-4">
        <h5>Información general</h5>
      </div>

      <div class="col-md-8">

        <div class="form-group">
          <div class="form-group">
            <label>Nombre:</label>
            <input class="form-control"
                   type="text"
                   required
                   name="nombre"
                   value="{{ old('nombre') ?? $lider->nombre }}">
            @if ($errors->has('nombre'))
              <div class="alert alert-danger">
                {{ $errors->first('nombre') }}
              </div>
            @endif
          </div>
        </div>

        <div class="form-group">
          <div class="form-group">
            <label>Biografía:</label>
            <textarea class="form-control"
                      name="bio"
                      rows="5"
                      value="">{{ old('bio') ?? $lider->bio }}</textarea>
            @if ($errors->has('bio'))
              <div class="alert alert-danger">
                {{ $errors->first('bio') }}
              </div>
            @endif
          </div>
        </div>

        <div class="form-group">
          <label>Posición:</label>
          <select id="posicion"
                  class="selectpicker form-control"
                  title="Seleccione una opción"
                  data-live-search="true"
                  required
                  name="posicion">
            @foreach(POSICIONES as $posicion)
              <option value="{{ $posicion }}">{{ $posicion }}</option>
            @endforeach
          </select>
          @if ($errors->has('posicion'))
            <div class="alert alert-danger">
              {{ $errors->first('posicion') }}
            </div>
          @endif
        </div>

      </div>
    </div>
    <!-- fin row 1 -->

    <hr>

    <!-- row 2 -->
    <div class="row">
      <div class="col-md-4">
        <h5>Información complementaria</h5>
      </div>

      <div class="col-md-8">

        <div class="form-group">
          <label>Contacto:</label> <br>
          <small>
            <label class="text-muted">
              Ingrese una forma de contacto escribiendo el nombre de la red social,
              dos puntos (:)
              y luego el nombre de usuario. Ejemplo: <strong>instagram:luciano27</strong>.
              Ingrese varias formas de contacto separados por espacio ( ). Ejemplo:
              <strong>instagram:veritatis facebook:voluptas email:nadia81@terra.com</strong>.
            </label>
          </small>
          <input class="form-control"
                 type="text"
                 required
                 name="contacto"
                 value="{{ old('contacto') ?? $lider->contacto }}">
          @if ($errors->has('contacto'))
            <div class="alert alert-danger">
              {{ $errors->first('contacto') }}
            </div>
          @endif
        </div>

        <div class="form-group">
          <label>Imagen:</label>
          <div class="custom-file"
               style="display:none">
            <input id="imagen"
                   class="custom-file-input"
                   type="file"
                   name="imagen"
                   lang="es">
            <label class="custom-file-label"
                   for="imagen">Elegir imagen</label>
          </div>
          <subir-imagen>@include('parciales.cargando-img')</subir-imagen>

          @if ($errors->has('imagen'))
            <div class="alert alert-danger">
              {{ $errors->first('imagen') }}
            </div>
          @endif
        </div>

      </div>
    </div>
    <!-- fin row 2 -->

    <hr>

    <div class="d-flex justify-content-center">
      <button type="submit" class="btn btn-primary mr-2">Guardar</button>
      <a class="btn btn-secondary" href="{{ route('admin.lideres.index') }}">Cancelar</a>
    </div>

  </form>


@endsection
@push('script')
<script>
  $('#imagen').on('change',function(){
    var fileName = $(this).val().replace('C:\\fakepath\\', '');
    $(this).next('.custom-file-label').html(fileName);
  });

  // valor de dropdown posicion
  $('#posicion').val(@json(old('posicion'))
    ? @json(old('posicion'))
    : @json($lider->posicion)).change();


</script>
@endpush

resources/views/sitio/admin/lideres/index.blade.php
@extends('sitio.admin.layout.admin_master')
@section('titulo', 'Listado de Líderes')
@push('style')
  @routes
@endpush
@section('admin_contenido')
    <h1>Listado de líderes</h1>

    <a class="btn btn-primary mb-1" href="{{ route('admin.lideres.create') }}">Crear Líder</a>

    <!-- cargar tabla vue -->
    <listado-lideres>@include('parciales.cargando-img')</listado-lideres>

@endsection